### ISSUE TITLE
Dropdown cut off by parent div

### ISSUE THREAD

**Issue by harvanchik** [ibirrer/headlessui-angular#2]
Any idea how I can solve this issue?

![image](https://user-images.githubusercontent.com/66141166/116756400-e1ada280-a9c0-11eb-8136-8d2301e66d69.png)

**Comment by harvanchik** [comment]
Just want to bump this.  I've already tried messing with the z-index, but I've had no luck.

**Comment by ibirrer** [comment]
The demo project contains an example, that uses the angular material cdk overlay utility. It might help you to solve the issue. See https://github.com/ibirrer/headlessui-angular/blob/main/projects/demo/src/app/app.component.html#L100.

Check out https://material.angular.io/cdk/overlay/overview for details. Note that you need to [import the cdk overlay styles](https://github.com/ibirrer/headlessui-angular/blob/main/projects/demo/src/styles.scss#L5) and of course add the angular cdk to your package.json.

**Comment by harvanchik** [comment]
Alright, I'll give that a try soon.

**Comment by harvanchik** [comment]
Closing for now, but will re-open if need be.
